### ISSUE TITLE
Arg<T>.Is.Equal and Arg<T>.Is.Same do not work with Expressions

### ISSUE THREAD

**Issue by jeremycampbellaustin** [ladeak/TestUpdaterAnalyzers#1]
The code is doing an implicit cast to an IdentifierNameSyntax which is resulting in null for expressions.

**Comment by jeremycampbellaustin** [comment]
@ladeak I have this fixed in a branch and tried to push, but getting a 403.   Do I need to be given access to the repo?

C:\Projects\TestUpdaterAnalyzers>git push --set-upstream origin Issue1-Equals-Same-Expression
info: please complete authentication in your browser...
remote: Permission to ladeak/TestUpdaterAnalyzers.git denied to jeremycampbellaustin.
fatal: unable to access 'https://github.com/ladeak/TestUpdaterAnalyzers.git/': The requested URL returned error: 403

**Comment by ladeak** [comment]
Let me check the permissions,

**Comment by ladeak** [comment]
You will need to fork this repository, clone your fork, do the fix, push your changes to your remote fork and open a PR (from your fork to this repo) with the fix.

**Comment by jeremycampbellaustin** [comment]
Thanks @ladeak.  PR is created.

**Comment by ladeak** [comment]
Release 0.1.16 should be out there. Give nuget a couple of minutes if you don't see it yet. In my experience, after updating the analyzer version in VS, you might need to restart VS itself.

**Comment by jeremycampbellaustin** [comment]
Verified issue is fixed.
